---
name: Lint Code Base
on: [push]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint with GitHub Super Linter
        uses: github/super-linter@v3
        env:
          LINTER_RULES_PATH: .  # Avoid having to create .github/linters/ dir
          VALIDATE_PYTHON_FLAKE8: true  # Code lint
          # GITHUB_TOKEN allows the GitHub Super Linter to mark the status of
          # each individual linter runs in the Checks sections of a pull request
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
